# Site settings
title: Flemzord
description: "Journal d'un OPS"
url: "http://127.0.0.1:4000"
baseurl: ""

# Sheekyll settings
logoUrl: https://pbs.twimg.com/profile_images/641139935467204608/k7C6u9cj.jpg
email: blog@flemzord.fr
homeArticle: 5
twitterUsername: Flemzord

# Build settings
markdown: kramdown
permalink: /:year/:title
