# Site settings
title: Flemzord
description: "Journal d'un OPS"
url: "https://www.flemzord.fr"
baseurl: ""

# Sheekyll settings
logoUrl: https://www.flemzord.fr/img/logo2.jpg
email: blog@flemzord.fr
homeArticle: 5
twitterUsername: Flemzord

# Build settings
markdown: kramdown
permalink: /:year/:title.html
